pipelines:
  test-pipeline: # name of pipeline
    group: Microservices
    materials:
      servicegit: # name of material
        git: https://github.com/SamiMe/bug.git
        branch: master
        username: SamiMe
        # encrypted_password:  AES:5CAkeW1grD015H1gewzwwQ==
        #secure_variables:
          #PASSWORD: AES:5CAkeW1grD015H1gewzwwQ==
        password: AES:5CAkeW1grD015H1gewzwwQ==
        destination: gitmaterialdir
#        auto_update: true
    stages:
      - print_pwd1: # name of stage
          clean_workspace: true
          #approval: manual
          jobs: # jobs are ran in parallel
            pwd: # name of job
              elastic_profile_id: alpine
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - "-c"
                    - "pwd && cd gitmaterialdir && ls"
