pipelines:
  test-pipeline: # name of pipeline
    group: Microservices
    materials:
      servicegit: # name of material
        git: https://github.com/SamiMe/bug.git
        username: SamiMe
        encrypted_password: AES:sGZ8kSqFR/6mAI29W1Pj3g==:cwjyjlpEwXe8Jto8iHjThA==
        branch: master
        destination: gitmaterialdir
#        auto_update: true
    stages:
      - print_pwd1: # name of stage
          clean_workspace: true
          #approval: manual
          jobs: # jobs are ran in parallel
            pwd: # name of job
              elastic_profile_id: alpine
              tasks:
               - exec:
                   command: bash
                   working_directory: gitmaterialdir
                   arguments:
                    - "-c"
                    - "pwd && ls"
